services:
  - type: web
    name: nischay-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ID_FERNET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
